# Generated by Django 4.2.6 on 2023-10-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gafa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solares', models.BooleanField()),
                ('miopia_right', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('astigmatismo_right', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('hipermetropia_right', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('miopia_left', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('astigmatismo_left', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('hipermetropia_left', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('img', models.ImageField(upload_to='gafa_images/')),
                ('state_choices', models.CharField(choices=[('1', 'Bueno'), ('2', 'Muy Bueno'), ('3', 'Excelente')], max_length=1)),
            ],
        ),
    ]
