# Generated by Django 4.2.6 on 2023-10-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resight', '0002_alter_gafa_astigmatismo_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gafa',
            name='vendido',
            field=models.BooleanField(null=True),
        ),
    ]
