# Generated by Django 4.2.6 on 2023-10-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resight', '0003_gafa_vendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gafa',
            name='vendido',
            field=models.BooleanField(),
        ),
    ]
